version: '3'

services:
#  frontend:
#    build:
#      context: ./projectName-frontend
#      dockerfile: Dockerfile.frontend
#    ports:
#      - "8080:80"

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile.backend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - database

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
